"""
Base Strategy Class

Abstract base class for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional
import numpy as np


class SignalType(Enum):
    """Types of trading signals."""
    ENTRY_LONG = "entry_long"
    ENTRY_SHORT = "entry_short"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    NO_ACTION = "no_action"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    signal_type: SignalType
    instrument: str
    strength: float = 0.0  # 0.0 to 1.0 confidence
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    size_pct: float = 1.0  # Suggested position size as % of max allowed
    indicators: Dict[str, Any] = field(default_factory=dict)
    notes: str = ""
    
    @property
    def is_entry(self) -> bool:
        return self.signal_type in (SignalType.ENTRY_LONG, SignalType.ENTRY_SHORT)
    
    @property
    def is_exit(self) -> bool:
        return self.signal_type in (
            SignalType.EXIT_LONG, SignalType.EXIT_SHORT,
            SignalType.STOP_LOSS, SignalType.TAKE_PROFIT
        )
    
    @property
    def side(self) -> str:
        """Return 'long', 'short', or 'none'."""
        if self.signal_type in (SignalType.ENTRY_LONG, SignalType.EXIT_SHORT):
            return "long"
        elif self.signal_type in (SignalType.ENTRY_SHORT, SignalType.EXIT_LONG):
            return "short"
        return "none"


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.
    
    All strategies must implement:
    - name: Strategy identifier
    - timeframe: Primary candle timeframe
    - analyze(): Main analysis method returning a Signal
    """
    
    name: str = "base"
    timeframe: str = "1H"  # Primary timeframe
    secondary_timeframe: Optional[str] = None  # For multi-TF strategies
    
    def __init__(self, params: Optional[Dict[str, Any]] = None):
        """Initialize strategy with optional parameters."""
        self.params = params or {}
        self._setup_params()
    
    def _setup_params(self):
        """Override to set up strategy-specific parameters."""
        pass
    
    @abstractmethod
    def analyze(
        self,
        klines: List[Dict[str, Any]],
        current_position: Optional[Dict[str, Any]] = None,
        secondary_klines: Optional[List[Dict[str, Any]]] = None,
    ) -> Signal:
        """
        Analyze market data and generate a trading signal.
        
        Args:
            klines: List of candle dicts with keys: ts, open, high, low, close, volume
            current_position: Current position info if any
            secondary_klines: Secondary timeframe data for multi-TF strategies
            
        Returns:
            Signal object with action recommendation
        """
        pass
    
    # ==================== Technical Indicators ====================
    
    @staticmethod
    def ema(data: List[float], period: int) -> List[float]:
        """Calculate Exponential Moving Average."""
        if len(data) < period:
            return [np.nan] * len(data)
            
        ema = [np.nan] * (period - 1)
        multiplier = 2 / (period + 1)
        
        # First EMA = SMA
        ema.append(sum(data[:period]) / period)
        
        for price in data[period:]:
            ema.append((price - ema[-1]) * multiplier + ema[-1])
            
        return ema
    
    @staticmethod
    def sma(data: List[float], period: int) -> List[float]:
        """Calculate Simple Moving Average."""
        if len(data) < period:
            return [np.nan] * len(data)
            
        sma = [np.nan] * (period - 1)
        for i in range(period - 1, len(data)):
            sma.append(sum(data[i - period + 1:i + 1]) / period)
            
        return sma
    
    @staticmethod
    def rsi(data: List[float], period: int = 14) -> List[float]:
        """Calculate Relative Strength Index."""
        if len(data) < period + 1:
            return [np.nan] * len(data)
            
        deltas = [data[i] - data[i-1] for i in range(1, len(data))]
        
        gains = [d if d > 0 else 0 for d in deltas]
        losses = [-d if d < 0 else 0 for d in deltas]
        
        rsi_values = [np.nan] * period
        
        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period
        
        if avg_loss == 0:
            rsi_values.append(100)
        else:
            rs = avg_gain / avg_loss
            rsi_values.append(100 - (100 / (1 + rs)))
        
        for i in range(period, len(deltas)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period
            
            if avg_loss == 0:
                rsi_values.append(100)
            else:
                rs = avg_gain / avg_loss
                rsi_values.append(100 - (100 / (1 + rs)))
                
        return rsi_values
    
    @staticmethod
    def atr(
        highs: List[float],
        lows: List[float],
        closes: List[float],
        period: int = 14
    ) -> List[float]:
        """Calculate Average True Range."""
        if len(highs) < period + 1:
            return [np.nan] * len(highs)
            
        tr = [highs[0] - lows[0]]
        for i in range(1, len(highs)):
            tr.append(max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i-1]),
                abs(lows[i] - closes[i-1])
            ))
            
        atr_values = [np.nan] * (period - 1)
        atr_values.append(sum(tr[:period]) / period)
        
        for i in range(period, len(tr)):
            atr_values.append((atr_values[-1] * (period - 1) + tr[i]) / period)
            
        return atr_values
    
    @staticmethod
    def adx(
        highs: List[float],
        lows: List[float],
        closes: List[float],
        period: int = 14
    ) -> List[float]:
        """Calculate Average Directional Index."""
        if len(highs) < period * 2:
            return [np.nan] * len(highs)
            
        # Calculate +DM and -DM
        plus_dm = [0.0]
        minus_dm = [0.0]
        tr = [highs[0] - lows[0]]
        
        for i in range(1, len(highs)):
            up_move = highs[i] - highs[i-1]
            down_move = lows[i-1] - lows[i]
            
            plus_dm.append(up_move if up_move > down_move and up_move > 0 else 0)
            minus_dm.append(down_move if down_move > up_move and down_move > 0 else 0)
            
            tr.append(max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i-1]),
                abs(lows[i] - closes[i-1])
            ))
        
        # Smooth TR, +DM, -DM
        def smooth(data, period):
            smoothed = [sum(data[:period])]
            for i in range(period, len(data)):
                smoothed.append(smoothed[-1] - smoothed[-1]/period + data[i])
            return smoothed
            
        tr_smooth = smooth(tr, period)
        plus_dm_smooth = smooth(plus_dm, period)
        minus_dm_smooth = smooth(minus_dm, period)
        
        # Calculate +DI and -DI
        plus_di = [100 * p / t if t != 0 else 0 
                   for p, t in zip(plus_dm_smooth, tr_smooth)]
        minus_di = [100 * m / t if t != 0 else 0 
                    for m, t in zip(minus_dm_smooth, tr_smooth)]
        
        # Calculate DX and ADX
        dx = [100 * abs(p - m) / (p + m) if (p + m) != 0 else 0 
              for p, m in zip(plus_di, minus_di)]
        
        adx_values = [np.nan] * (period * 2 - 1)
        adx_values.append(sum(dx[:period]) / period)
        
        for i in range(period, len(dx)):
            adx_values.append((adx_values[-1] * (period - 1) + dx[i]) / period)
            
        # Pad to match input length
        while len(adx_values) < len(highs):
            adx_values.insert(0, np.nan)
            
        return adx_values
    
    @staticmethod
    def vwap(
        highs: List[float],
        lows: List[float],
        closes: List[float],
        volumes: List[float]
    ) -> tuple:
        """
        Calculate VWAP and standard deviation bands.
        
        Returns:
            (vwap, upper_band, lower_band) - 2 standard deviation bands
        """
        typical_prices = [(h + l + c) / 3 for h, l, c in zip(highs, lows, closes)]
        
        cum_vol = 0.0
        cum_tp_vol = 0.0
        cum_tp_vol_sq = 0.0
        
        vwap_values = []
        upper_band = []
        lower_band = []
        
        for tp, vol in zip(typical_prices, volumes):
            cum_vol += vol
            cum_tp_vol += tp * vol
            cum_tp_vol_sq += (tp ** 2) * vol
            
            if cum_vol == 0:
                vwap_values.append(tp)
                upper_band.append(tp)
                lower_band.append(tp)
            else:
                vwap = cum_tp_vol / cum_vol
                variance = (cum_tp_vol_sq / cum_vol) - (vwap ** 2)
                std_dev = np.sqrt(max(0, variance))
                
                vwap_values.append(vwap)
                upper_band.append(vwap + 2 * std_dev)
                lower_band.append(vwap - 2 * std_dev)
                
        return vwap_values, upper_band, lower_band
    
    @staticmethod
    def roc(data: List[float], period: int = 10) -> List[float]:
        """Calculate Rate of Change."""
        roc_values = [np.nan] * period
        
        for i in range(period, len(data)):
            if data[i - period] != 0:
                roc_values.append(((data[i] - data[i - period]) / data[i - period]) * 100)
            else:
                roc_values.append(0)
                
        return roc_values
    
    @staticmethod
    def highest(data: List[float], period: int) -> List[float]:
        """Calculate rolling highest value."""
        result = [np.nan] * (period - 1)
        for i in range(period - 1, len(data)):
            result.append(max(data[i - period + 1:i + 1]))
        return result
    
    @staticmethod
    def lowest(data: List[float], period: int) -> List[float]:
        """Calculate rolling lowest value."""
        result = [np.nan] * (period - 1)
        for i in range(period - 1, len(data)):
            result.append(min(data[i - period + 1:i + 1]))
        return result
    
    # ==================== Helpers ====================
    
    def extract_ohlcv(self, klines: List[Dict]) -> tuple:
        """Extract OHLCV arrays from klines list."""
        opens = [k["open"] for k in klines]
        highs = [k["high"] for k in klines]
        lows = [k["low"] for k in klines]
        closes = [k["close"] for k in klines]
        volumes = [k["volume"] for k in klines]
        return opens, highs, lows, closes, volumes
    
    def no_signal(self, instrument: str) -> Signal:
        """Return a no-action signal."""
        return Signal(
            signal_type=SignalType.NO_ACTION,
            instrument=instrument,
            strength=0.0
        )
